### ISSUE TITLE
Barcode is not displayed

### ISSUE THREAD

**Issue by raxod502** [conduition/ticketgimp#1]
On Android 14 (GrapheneOS) using Firefox as the default browser, and running the app from this repo through Expo Go, everything loads properly, except that nothing happens no matter what text is typed or pasted into the box. I would expect to at least see an error message if the input is invalid.

<img src="https://github.com/user-attachments/assets/0116faa4-89dd-4b9e-aa1d-2e12832224ad" width="200px" />

An actual ticket token, as obtained (to my understanding) from the response to the `https://my.ticketmaster.com/deliver-tickets/async/json/order/xxxxxx/ret?safeTix=true` POST request which contains a url `https://my.ticketmaster.com/deliver-tickets/async/json/xxxxxx/ret/poll?token=xxxxxx`, is 288 hexadecimal characters, but it produces the same result as the screenshot above.

I don't see anything in the Expo Go log. I also tried using Expo to open the JavaScript inspector, but for some reason it doesn't seem to support Firefox, so I didn't pursue that further - I can work it out if that would be helpful.

```
Error launching JS inspector: [findSupportedBrowserTypeAsync] Unable to find a browser on the host to open the inspector. Supported browsers: Google Chrome, Microsoft Edge, Brave
```

**Comment by conduition** [comment]
TicketGimp expects a ticket secret that matches the format [described in my blog post here](https://conduition.io/coding/ticketmaster/#Here%E2%80%99s-the-Secret). If the input text doesn't match the expected format, the app simply ignores the input. i was lazy and didn't want to code an error box, as TicketGimp is more of an educational demo than something intended for end-users.

If you'd like to see how the ticket secret is actually parsed in the app, see [this code](https://github.com/conduition/ticketgimp/blob/main/App.js#L24-L62). 

Try this and see if it works:

```
eyJiIjoiNDgxODQ4NTkwMTAySyIsInQiOiJUR1JMWUNxQWYyQ1MvQmxILzh5dThZdkhoV055TW8xUW9CYTI5UTVqVkN4V2xBcE5NbnczSlJkeU9UcFVVWUFDIiwiY2siOiJiOTg0MzJlZDIzYjhmMmJkYTgyMzQ4MjE2MjI5ZjRkMjdjZTlkMDYzIiwiZWsiOiJiMzUxOTM2NGUwYzc5MTRjMWY5ZDU5ZDM1NjUyYTA0MDY3ZDJmNjQ3IiwicnQiOiJyb3RhdGluZ19zeW1ib2xvZ3kifQ==
```

^ That is a base64 string which decodes into the following UTF8 data:

```json
{"b":"481848590102K","t":"TGRLYCqAf2CS/BlH/8yu8YvHhWNyMo1QoBa29Q5jVCxWlApNMnw3JRdyOTpUUYAC","ck":"b98432ed23b8f2bda82348216229f4d27ce9d063","ek":"b3519364e0c7914c1f9d59d35652a04067d2f647","rt":"rotating_symbology"}
```

If your ticket matches that format then TicketGimp should be able to decode it and display the barcode. Otherwise maybe it's a problem with the WebView?

**Comment by raxod502** [comment]
Yes, I'm sorry, I extracted the wrong token. I was using the web client rather than the mobile application, since it's more convenient. The web client also displays bar codes, but only if you supply a user agent that suggests it is a mobile browser. It does however seem to fetch the token from a different endpoint.

Specifically, repeated GET requests are made to `https://my.ticketmaster.com/deliver-tickets/async/json/somebase64string/ret/poll?token=hex288chars` which receive 202 responses and eventually a 200 response with `tokenMap => $orderId => barcode` attributes that have a token in the desired format.

Unfortunately, with the web client, it does not log the token directly to the JavaScript console; it seems that was either patched out since the blog article was posted, or is differing behavior between the two clients.

One interesting thing to note is that if multiple tickets are held, then barcode tokens are returned for all of them, even if some of them are marked as "pending transfer" to another user, and therefore do not have their barcodes displayed in the user interface.

Also, there is another similar endpoint `https://my.ticketmaster.com/deliver-tickets/async/json/order/somebase64string/poll?eventId=somebase64string&token=hex288chars` which is polled for 202s and then a 200, but it is different and should be ignored.

I hope these notes can be of assistance to anyone else who wishes to generate Ticketmaster barcodes.

**Comment by conduition** [comment]
> Unfortunately, with the web client, it does not log the token directly to the JavaScript console; it seems that was either patched out since the blog article was posted, or is differing behavior between the two clients.


Interesting! Ticketmaster must have patched that out, as I was using the mobile web client myself. 

However, you can probably add the console.log statement back in, using a browser devtools to edit the source code in the live web-page. You might need to enable USB debugging on your phone, which is a pain to get working on some phones but should ultimately be doable. I'd recommend using chrome on both mobile and desktop as its devtools USB connection tends to work more reliably.

**Comment by farewelltospring** [comment]
Is there any additional step you have to take to load the ticket barcode page on the browser? I tried to spoof the user agent but it just told me to use the app.

**Comment by conduition** [comment]
Maybe ticketmaster disabled ticket viewing on web browsers completely, in an attempt to prevent people from getting their ticket secrets. I haven't looked into this in a long time, but in theory the only way to get the ticket secret in that case would be to reverse engineer their API or mobile app. Yet another step in the cat & mouse game ticketmaster is playing to keep people from owning their tickets.

One possible avenue: Install the TM app, view the ticket barcode, and then use a tool like [Frida](https://frida.re/docs/android/) to dump the TM application memory, then extract the ticket secret from that dump. For example, [this tool](https://github.com/Nightbringer21/fridump) seems to do what you'd need.
